# Generated by Django 3.2.8 on 2023-04-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dish_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='Receipt',
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name_plural': 'Receipts'},
        ),
    ]
