# Generated by Django 3.2.8 on 2023-04-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230413_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
