# Generated by Django 3.2.8 on 2023-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='img',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
