# Generated by Django 3.2.8 on 2023-04-18 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_post_alter_receipt_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Receipts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='cooking_time',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='null', upload_to='dishes/'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.type'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
