# Generated by Django 3.2.8 on 2023-04-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230418_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default=None, upload_to='dishes/'),
        ),
    ]
