# Generated by Django 3.2.8 on 2023-04-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20230419_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Receipt',
        ),
    ]
