# Generated by Django 3.2.8 on 2023-04-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_post_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name_plural': 'Receipts'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
