# Generated by Django 3.2.8 on 2023-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20230419_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='instruction',
            field=models.TextField(default='Пока не добавлено'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.CharField(default='30', max_length=30),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
