# Generated by Django 3.2.8 on 2023-04-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20230425_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='receipt',
        ),
        migrations.RenameField(
            model_name='purchased',
            old_name='product',
            new_name='receipt',
        ),
    ]
